import { get,list,put } from "@vercel/blob";
import type { SuiteUser } from "./auth";
import type { ProviderOrganization,ServiceOffer,ServiceRequest,ServiceReview } from "./model";

const P={offers:"services-v1/offers/",requests:"services-v1/requests/",reviews:"services-v1/reviews/",organizations:"network-v1/organizations/",workspaces:"company-v1/workspaces/"};
type OrganizationRecord={id:string;ownerId:string;name:string;model:"capitalista"|"tecnosocialista";city:string;status:string};
type WorkspaceRecord={organizationId:string;members:{userId?:string;email:string;status:string}[]};
const seedDate="2026-07-01T10:00:00.000Z";
export const seedOffers:ServiceOffer[]=[
  {id:"seed-tech-1",providerId:"seed-p1",providerName:"Officina Comune",providerType:"organizzazione",organizationId:"seed-officina",organizationModel:"tecnosocialista",category:"tecnico",subcategory:"Riparazioni",title:"Riparazione piccoli elettrodomestici",description:"Diagnosi, riparazione e spiegazione dell'intervento. Priorità al recupero dei componenti e al riuso.",tags:["riparazione","riuso","casa"],mode:"luogo",city:"Milano",radiusKm:15,place:{name:"Officina Comune",address:"Zona Lambrate",city:"Milano",accessibility:"Piano strada, accessibile"},availability:"Mar–Sab · 09:00–18:00",durationMinutes:60,marketPrice:35,askingPrice:25,priceUnit:"intervento",languages:["Italiano","Inglese"],verification:"non-richiesta",rating:4.9,ratingCount:84,completedCount:127,status:"pubblicato",createdAt:seedDate},
  {id:"seed-tech-2",providerId:"seed-p2",providerName:"Nora Bianchi",providerType:"persona",category:"tecnico",subcategory:"Assistenza digitale",title:"Assistenza computer e smartphone",description:"Configurazione, sicurezza di base, backup e recupero dell'autonomia digitale, anche a distanza.",tags:["computer","smartphone","sicurezza"],mode:"ibrido",city:"Roma",radiusKm:20,availability:"Feriali · 17:00–21:00",durationMinutes:45,marketPrice:30,askingPrice:18,priceUnit:"ora",languages:["Italiano"],verification:"non-richiesta",rating:4.8,ratingCount:52,completedCount:79,status:"pubblicato",createdAt:seedDate},
  {id:"seed-health-1",providerId:"seed-p3",providerName:"Dott.ssa Elena Mori",providerType:"persona",category:"salute",subcategory:"Fisioterapia",title:"Valutazione fisioterapica e percorso motorio",description:"Valutazione funzionale e percorso individuale in studio o a domicilio. Non è un servizio di emergenza.",tags:["fisioterapia","movimento","prevenzione"],mode:"ibrido",city:"Bologna",radiusKm:12,place:{name:"Spazio Movimento",address:"Quartiere Porto",city:"Bologna",accessibility:"Ascensore e bagno accessibile"},availability:"Lun–Ven · 08:00–19:00",durationMinutes:50,marketPrice:55,askingPrice:45,priceUnit:"sessione",languages:["Italiano","Inglese"],qualification:"Fisioterapista",registerReference:"Albo verificato",verification:"verificata",rating:4.9,ratingCount:67,completedCount:96,status:"pubblicato",createdAt:seedDate},
  {id:"seed-care-1",providerId:"seed-p4",providerName:"Rete Cura di Quartiere",providerType:"organizzazione",organizationId:"seed-cura",organizationModel:"tecnosocialista",category:"cura",subcategory:"Accompagnamento",title:"Accompagnamento e commissioni di prossimità",description:"Supporto per visite, spesa, pratiche e spostamenti quotidiani, organizzato da persone del territorio.",tags:["accompagnamento","anziani","territorio"],mode:"domicilio",city:"Bologna",radiusKm:10,availability:"Tutti i giorni · 08:00–20:00",durationMinutes:90,marketPrice:18,askingPrice:10,priceUnit:"ora",languages:["Italiano","Arabo","Inglese"],verification:"non-richiesta",rating:4.8,ratingCount:113,completedCount:204,status:"pubblicato",createdAt:seedDate},
  {id:"seed-learn-1",providerId:"seed-p5",providerName:"Samir Conti",providerType:"persona",category:"didattica",subcategory:"Tecnologia",title:"Programmazione web da zero",description:"Lezioni individuali o in piccolo gruppo, orientate a costruire un progetto reale e comprensibile.",tags:["web","javascript","peer-to-peer"],mode:"online",city:"Online",radiusKm:0,availability:"Mar e Gio · 18:00–21:00",durationMinutes:60,marketPrice:28,askingPrice:0,priceUnit:"gratuito",languages:["Italiano","Francese"],verification:"non-richiesta",rating:4.9,ratingCount:41,completedCount:63,status:"pubblicato",createdAt:seedDate},
  {id:"seed-learn-2",providerId:"seed-p6",providerName:"Laboratorio Parole",providerType:"organizzazione",category:"didattica",subcategory:"Lingue",title:"Italiano pratico in piccoli gruppi",description:"Conversazione, documenti quotidiani e autonomia linguistica. Gruppi di massimo sei persone.",tags:["italiano","gruppo","inclusione"],mode:"ibrido",city:"Torino",radiusKm:8,place:{name:"Casa del Quartiere",address:"Zona San Salvario",city:"Torino",accessibility:"Ingresso accessibile"},availability:"Mer e Sab · più fasce",durationMinutes:75,marketPrice:20,askingPrice:5,priceUnit:"sessione",languages:["Italiano","Inglese","Arabo"],verification:"non-richiesta",rating:4.7,ratingCount:36,completedCount:58,status:"pubblicato",createdAt:seedDate},
];

export async function loadServices(user?:SuiteUser|null){
  if(!process.env.BLOB_READ_WRITE_TOKEN)return{offers:seedOffers,requests:[] as ServiceRequest[],reviews:[] as ServiceReview[],organizations:[] as ProviderOrganization[]};
  const[storedOffers,requests,reviews,organizations,workspaces]=await Promise.all([listRecords<ServiceOffer>(P.offers),listRecords<ServiceRequest>(P.requests),listRecords<ServiceReview>(P.reviews),listRecords<OrganizationRecord>(P.organizations),listRecords<WorkspaceRecord>(P.workspaces)]);
  const offers=unique([...storedOffers,...seedOffers]).filter((offer)=>offer.status==="pubblicato"||offer.providerId===user?.id).map((offer)=>withRating(offer,reviews));
  const accessible=user?organizations.filter((organization)=>organization.status==="attiva"&&(organization.ownerId===user.id||workspaces.some((workspace)=>workspace.organizationId===organization.id&&workspace.members.some((member)=>member.userId===user.id||normalize(member.email)===normalize(user.email))))):[];
  return{offers:newest(offers),requests:user?newest(requests.filter((request)=>request.requesterId===user.id||request.providerId===user.id)):[],reviews:newest(reviews),organizations:accessible.map((item)=>({id:item.id,name:item.name,model:item.model,city:item.city}))};
}
export async function findService(id:string){return seedOffers.find((item)=>item.id===id)??(validId(id)?readJson<ServiceOffer>(`${P.offers}${id}.json`):null)}
export async function saveOffer(value:ServiceOffer){return writeJson(`${P.offers}${value.id}.json`,value,false)}
export async function saveRequest(value:ServiceRequest){return writeJson(`${P.requests}${value.id}.json`,value,false)}
export async function findRequest(id:string){return validId(id)?readJson<ServiceRequest>(`${P.requests}${id}.json`):null}
export async function updateRequest(value:ServiceRequest){return writeJson(`${P.requests}${value.id}.json`,value,true)}
export async function saveReview(value:ServiceReview){return writeJson(`${P.reviews}${value.id}.json`,value,false)}
export async function hasReview(requestId:string,userId:string){return(await listRecords<ServiceReview>(P.reviews)).some((item)=>item.requestId===requestId&&item.authorId===userId)}
function withRating(offer:ServiceOffer,reviews:ServiceReview[]){const related=reviews.filter((item)=>item.serviceId===offer.id);if(!related.length)return offer;const total=offer.rating*offer.ratingCount+related.reduce((sum,item)=>sum+item.rating,0);const count=offer.ratingCount+related.length;return{...offer,rating:Number((total/count).toFixed(1)),ratingCount:count}}
async function listRecords<T>(prefix:string){try{const result=await list({prefix,limit:1000});const records=await Promise.all(result.blobs.map((blob)=>readJson<T>(blob.url)));return records.flatMap((item)=>item===null?[]:[item])}catch{return[]}}
async function writeJson(path:string,value:unknown,overwrite:boolean){await put(path,JSON.stringify(value),{access:"private",addRandomSuffix:false,allowOverwrite:overwrite,contentType:"application/json; charset=utf-8",cacheControlMaxAge:0});return value}
async function readJson<T>(urlOrPath:string):Promise<T|null>{try{const result=await get(urlOrPath,{access:"private",useCache:false});if(!result||result.statusCode!==200)return null;return JSON.parse(await new Response(result.stream).text()) as T}catch{return null}}
function newest<T extends{createdAt:string}>(items:T[]){return items.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,500)}
function unique<T extends{id:string}>(items:T[]){return[...new Map(items.map((item)=>[item.id,item])).values()]}
function normalize(value:string){return value.trim().toLocaleLowerCase("it")}
function validId(value:string){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
